version: '2'
services:
  web:
    build: .
    ports:
      - "5005:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:06mrtnsrn@db:5432/kombinledb
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres #
      POSTGRES_PASSWORD: 06mrtnsrn #
      POSTGRES_DB: kombinledb
    ports:
      - "5432:5432"

      #db kur
      #environmental veriable instead of password username
      #redis
      #decorator  
      