version: '2'
services:
  web:
    build: .
    ports:
      - "5005:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AIRECOG_URL=http://airecog:5001 
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - .:/app
    env_file:
      - .flaskenv

  db:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .flaskenv
    volumes:
      - db-data:/var/lib/postgresql/data
  
volumes:
  db-data: